// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEa4e88BjRKcJkzlEQPFqgI_1q-v1Eiio',
    appId: '1:225066926584:web:85bda04e017599ae38960d',
    messagingSenderId: '225066926584',
    projectId: 'trackly-e1081',
    authDomain: 'trackly-e1081.firebaseapp.com',
    storageBucket: 'trackly-e1081.firebasestorage.app',
    measurementId: 'G-BJ8ZGPQBT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaD5ewK3lGxwro8eefwyYv9eluGv9zfLk',
    appId: '1:225066926584:android:039f4a3942172e8638960d',
    messagingSenderId: '225066926584',
    projectId: 'trackly-e1081',
    storageBucket: 'trackly-e1081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0jU1svjhHHSssdsNarH1rFsg_NYPQTY',
    appId: '1:225066926584:ios:b946c9cc7c23ac3b38960d',
    messagingSenderId: '225066926584',
    projectId: 'trackly-e1081',
    storageBucket: 'trackly-e1081.firebasestorage.app',
    iosClientId: '225066926584-b7cveoruh600uei8gm5b8es0q32erhpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0jU1svjhHHSssdsNarH1rFsg_NYPQTY',
    appId: '1:225066926584:ios:b946c9cc7c23ac3b38960d',
    messagingSenderId: '225066926584',
    projectId: 'trackly-e1081',
    storageBucket: 'trackly-e1081.firebasestorage.app',
    iosClientId: '225066926584-b7cveoruh600uei8gm5b8es0q32erhpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEa4e88BjRKcJkzlEQPFqgI_1q-v1Eiio',
    appId: '1:225066926584:web:f85da009f7afd7b738960d',
    messagingSenderId: '225066926584',
    projectId: 'trackly-e1081',
    authDomain: 'trackly-e1081.firebaseapp.com',
    storageBucket: 'trackly-e1081.firebasestorage.app',
    measurementId: 'G-RGEMMNZQ56',
  );
}
